flowchart LR

    linkStyle default stroke:#555555

    Client0[Client] -.- Item0
    Client0 -.- Item1
    Client1[Client] -.- Item1

    subgraph Store0 [Store]
    Item0(Item)
    Item1(Item)
    Item2(Item)
    end

    Item0 <--> Proto0([REQ+SUB<br>protocol])
    Item1 <--> Proto0
    Item2 <--> Proto0
    Proto0 <--> ZMQ0(((Transport)))

    style Client0 fill:#adf5ff,color:black
    style Client1 fill:#adf5ff,color:black
    style Item0 fill:#fff5ad,color:black,stroke:#888888
    style Item1 fill:#fff5ad,color:black,stroke:#888888
    style Item2 fill:#fff5ad,color:black,stroke:#888888
    style Proto0 fill:#ececff,color:black,stroke:#888888
    style Store0 fill:#ffffde,color:black,stroke:#888888
    style ZMQ0 fill:#ececff,color:black,stroke:#888888
