sequenceDiagram
    autonumber
    Participant Daemon
    Participant Registry as Any Registry

    Daemon->>+Registry: Hello?
    Registry->>-Daemon: Try port 10234

    Daemon->>+Registry: SET: _config
    Registry->>-Daemon: REP: JSON payload
