#! /usr/bin/env python3

description = """
The registry daemon acts as a clearing house for configuration requests;
when daemons first start running they will seek out any registries on their
local network and announce configuration updates; any clients broadcasting
will discover a local registry, and ask for any available configuration
information.

Daemons and clients can both bypass broadcast discovery for a local registry
if they already know where to find a registry.
"""

import argparse
import logging
import socket
import sys
import threading
import time

import mktl

logging.basicConfig(format='%(created)f %(message)s', level=logging.INFO)
logger = logging.getLogger(__name__)


def main():

    # We don't use command line options here, but if we did, they would be
    # handled in parse_command_line(). At the very least, it handles the
    # case where the caller specifies -h on the command line.

    config = parse_command_line()
    main.hostname = socket.getfqdn()
    store = 'registry:' + main.hostname

    description = generate_description()
    mktl.config.authoritative(store, store, description)

    daemon = RegistryDaemon(store, store, override=True)
    beacon = mktl.protocol.discover.Server(daemon.rep.port)

    # Run discovery once upon startup, rely on daemon announcements to
    # learn of any additions to the local network.

    daemon.discover_daemons()


    delay = 30
    while True:
        try:
            main.shutdown.wait(delay)
        except (KeyboardInterrupt, SystemExit):
            break



main.hostname = None
main.shutdown = threading.Event()



def generate_description():

    items = dict()

    items['daemon_count'] = dict()
    items['daemon_count']['description'] = 'Quantity of active daemons seen by this registry.'
    items['daemon_count']['type'] = 'numeric'
    items['daemon_count']['initial'] = 0
    items['daemon_count']['settable'] = False

    items['log'] = dict()
    items['log']['description'] = 'Log message describing recent events.'
    items['log']['initial'] = ''
    items['log']['settable'] = False

    return items


def parse_command_line():

    arguments = dict()
    arguments['formatter_class'] = argparse.RawDescriptionHelpFormatter
    arguments['description'] = description
    ##arguments['epilog'] = epilog

    parser = argparse.ArgumentParser(**arguments)

    parsed = parser.parse_args()
    return parsed



class RegistryDaemon(mktl.Daemon):

    def setup(self):

        # This would normally be a call to self.add_get_handler() but
        # the _config concept is not a fully qualified item.

        self.rep._req_set_handlers['_config'] = self.req_set_config


    def check_keys(self, new, override):
        """ Confirm that any keys unique to this new configuration block are
            not present in any other blocks.
        """

        store = new['store']
        config = mktl.config.get(store)

        if len(config) == 0:
            # No previously stored blocks to check against. That means all of
            # the keys are unique, and there are no conflicts.
            return

        items = new['items']
        uuid = new['uuid']
        to_remove = set()

        for old_uuid in config.uuids():

            if uuid == old_uuid:
                # Doesn't make sense to check a block for duplicates against
                # any version of itself. Skip this one.
                continue

            old = config[old_uuid]
            running = None

            old_items = old['items']
            for key in old_items:
                if key in items:
                    if override == True:
                        if running is None:
                            running = self.check_running(old)

                        if running == True:
                            alias = old['alias']
                            old_port = old['provenance'][0]['rep']
                            old_host = old['provenance'][0]['hostname']
                            raise RuntimeError("%s contains %s, and is running at %s:%s" % (alias, key, old_host, old_port))
                        else:
                            # Override requested, and the old daemon is not
                            # running. Can't remove the UUID right now because
                            # we're busy iterating on it.
                            to_remove.add(uuid)

                    else:
                        alias = new['alias']
                        port = new['provenance'][0]['rep']
                        host = new['provenance'][0]['hostname']
                        logger.error("reject: %s from %s:%s (%s)" % (alias, host, port, uuid))
                        raise KeyError('key in new configuration block conflicts with an existing key: ' + key)

        # This set will be empty unless overrides were requested.

        for uuid in to_remove:
            try:
                block = config[uuid]
            except KeyError:
                # Already gone. Not entirely sure how that might have happened,
                # but it does, and there's no sense trying to remove it twice.
                continue

            alias = block['alias']
            port = block['provenance'][0]['rep']
            host = block['provenance'][0]['hostname']

            logger.info("forget: %s from %s:%s (%s)" % (alias, host, port, uuid))
            config.remove(uuid)


    def check_provenance(self, block):
        """ Look for provenance loops, and potentially (in the future) other
            problems with the provenance.
        """

        local_provenance = dict()
        local_provenance['hostname'] = main.hostname
        local_provenance['rep'] = self.rep.port

        if mktl.config.contains_provenance(block, local_provenance):
            raise ProvenanceLoopError('circular provenance detected')


    def check_running(self, block):
        """ Check to see whether the daemon associated with this
            configuration block is still running.
        """

        # Take advantage of a built-in keyword to probe whether the
        # remote daemon is online and answering questions.

        store = block['store']
        alias = block['alias']
        clock = '_' + alias + 'clk'
        key = store + '.' + clock

        payload = mktl.protocol.message.Payload(refresh=True)
        request = mktl.protocol.message.Request('GET', key, payload)

        # Traverse the provenance by highest stratum number first.

        provenance = block['provenance']
        provenance = list(provenance)
        provenance.reverse()

        for stratum in provenance:
            # Only an authoritative stratum will have a 'pub' entry.
            try:
                stratum['pub']
            except KeyError:
                continue

            hostname = stratum['hostname']
            port = stratum['rep']
            request.response = None

            try:
                payload = mktl.protocol.request.send(hostname, port, request)
            except TimeoutError:
                continue

            if payload.value is not None:
                return True

        return False


    def discover_daemons(self):

        discovered = mktl.protocol.discover.search_direct()

        for seen in discovered:

            address,port = seen
            request = mktl.protocol.message.Request('GET', '_hash')
            try:
                payload = mktl.protocol.request.send(address, port, request)
            except:
                logger.warning("HASH request from %s:%d failed" % (address, port))
                continue

            if payload:
                hashes = payload.value
            else:
                hashes = None

            if hashes is None:
                # Error requesting the hashes.
                logger.warning("HASH request from %s:%d failed" % (address, port))

                if payload:
                    error = payload.error
                else:
                    error = None

                if error:
                    e_type = error['type']
                    e_text = error['text']
                    e_debug = error['debug']
                    logger.warning("Remote exception: %s: %s\n%s" % (e_type, e_text, e_debug))
                continue

            for store in hashes.keys():
                request = mktl.protocol.message.Request('GET', store + '._config')
                payload = mktl.protocol.request.send(address, port, request)

                blocks = payload.value

                try:
                    error = payload.error
                except AttributeError:
                    error = None

                if error:
                    e_type = error['type']
                    e_text = error['text']
                    logger.warning("CONFIG request failed: %s: %s" % (e_type, e_text))

                if blocks:
                    for uuid,block in blocks.items():
                        block['override'] = True
                        try:
                            self.process_block(block)
                        except ProvenanceLoopError:
                            # This is us, discovering ourselves.
                            pass


    def process_block(self, new):

        print('processing: ' + repr(new))
        store = new['store']
        config = mktl.config.get(store)

        self.check_provenance(new)

        # If the only provenance entry is stratum zero this new block
        # is authoritative. If the daemon responsible for the block
        # is requesting an override we have to apply some additional
        # conditions to the checks embedded here.

        if len(new['provenance']) == 1:
            authoritative = True
        else:
            authoritative = False

        try:
            override = new['override']
        except KeyError:
            override = False
        else:
            # Won't be needing that going forward. The presence of an
            # override flag is only relevant right now, as part of these
            # checks being performed right here for an 'announce' operation.
            del new['override']

        uuid = new['uuid']
        alias = new['alias']

        try:
            old = config[uuid]
        except KeyError:
            old = None

        if old is None:
            # Maybe it's a different UUID, but the same alias.

            try:
                old = config[alias]
            except KeyError:
                pass

            if old and old['uuid'] != uuid and authoritative == True:
                if override == True:
                    running = self.check_running(old)
                    if running == True:
                        old_port = old['provenance'][0]['rep']
                        old_host = old['provenance'][0]['hostname']
                        new_port = new['provenance'][0]['rep']
                        new_host = new['provenance'][0]['hostname']
                        logger.error("reject: %s from %s:%s (%s)" % (alias, new_host, new_port, uuid))
                        raise RuntimeError("%s is running at %s:%s" % (alias, old_host, old_port))


        if old and authoritative == True:
            # Does the provenance match? If not, we need an override to
            # proceed, but even then we should only proceed if the previous
            # daemon is offline.

            match = mktl.config.match_provenance(old['provenance'], new['provenance'])
            if match == False and override == False:
                old_port = old['provenance'][0]['rep']
                old_host = old['provenance'][0]['hostname']
                new_port = new['provenance'][0]['rep']
                new_host = new['provenance'][0]['hostname']

                logger.error("reject: %s from %s:%s (%s)" % (alias, new_host, new_port, uuid))
                raise ValueError("%s expected to be running at %s:%s, you are %s:%s" % (alias, old_host, old_port, new_host, new_port))

            if match == False and override == True:
                running = self.check_running(old)

                if running == True:
                    port = old['provenance'][0]['rep']
                    host = old['provenance'][0]['hostname']
                    raise ValueError("%s daemon already running at %s:%s" % (alias, host, port))

                # Else the local configuration should be updated to reflect
                # this new configuration block. Remove the old one to streamline
                # further checks.

                port = old['provenance'][0]['rep']
                host = old['provenance'][0]['hostname']
                logger.info("forget: %s from %s:%s (%s)" % (alias, host, port, uuid))
                config.remove(uuid)

            # We've already seen a block for this UUID. Accept the new block
            # for processing if and only if it is different, or has a newer
            # timestamp than what we know.

            if old['hash'] == new['hash'] and old['time'] >= new['time']:
                # We already know this block.
                return

        # Reject a configuration block if it contains keys that collide
        # with another block in the cache. Not looking for a return
        # value from check_keys(), exceptions are raised when there are
        # problems.

        self.check_keys(new, override)

        # Now that all the checks have passed it's time to update the local
        # cache of configuration data.

        mktl.config.add_provenance(new, main.hostname, self.rep.port)
        port = new['provenance'][0]['rep']
        host = new['provenance'][0]['hostname']

        # Dynamically update the request handling to know how to handle
        # requests for the configuration for this store.

        key = store + '._config'
        self.rep._req_get_handlers[key] = self.req_get_config

        logger.info("remember: %s from %s:%s (%s)" % (alias, host, port, uuid))
        config.update(new)


    def req_get_config(self, request):
        """ We are expecting queries for hash and configuration data, aimed
            at special 'store._config' items.
        """

        target = request.target
        store, key = target.split('.', 1)

        try:
            config = mktl.config.get(store)
        except KeyError:
            payload_data = tuple()
        else:
            payload_data = config._by_uuid

        payload = mktl.Payload(value=payload_data)
        return payload


    def req_set_config(self, request):
        """ We are expecting queries for configuration data, aimed
            at specially named built-in keys.
        """

        # We could be inspecting the request.target value to ensure it
        # matches the provided configuration blocks. For now, just process
        # whatever we get.

        block = request.payload.value

        try:
            self.process_block(block)
        except ProvenanceLoopError:
            # This configuration block came from us. Pay no mind.
            pass

        payload = mktl.Payload(value=True)
        return payload


# end of class RegistryDaemon



class ProvenanceLoopError(RuntimeError):
    pass


if __name__ == '__main__':
    main()

# vim: set expandtab tabstop=8 softtabstop=4 shiftwidth=4 autoindent:
